- hosts: Nginx
  order: sorted
  become: yes
  tasks:
    - name: block ipv6 for apt
      copy:
        content: "Acquire::ForceIPv4 true;"
        dest: "/etc/apt/apt.conf.d/99force-ipv4"

    - name: Install nginx and goaccess
      apt:
        name: nginx, certbot, python3-certbot-nginx, goaccess
        state: present
        update_cache: yes

    - name: Remove server tokens
      command: sed -i 's/#server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf

    - name: Install Nginx configs
      copy:
        src: Configs/Nginx/
        dest: /etc/nginx/sites-available

    - name: Find all files in "sites-available"
      find:
        paths: /etc/nginx/sites-available
      register: find

    - name: Create symlinks to "sites-enabled"
      become: True
      file:
        src: "{{ item.path }}"
        path: "/etc/nginx/sites-enabled/{{ item.path | basename }}"
        state: link
      with_items: "{{ find.files }}"

    - name: Configure HTTPS with certbot
      command: "certbot --nginx --register-unsafely-without-email --expand --agree-tos --redirect -n --keep -d nextcloud.gwebs.ca -d bitwarden.gwebs.ca -d gabrieljean.com -d com2kube.io"
   
    - set_fact:
        goaccess-service: 'W1VuaXRdCkRlc2NyaXB0aW9uPUdvYWNjZXNzIFdlYiBsb2cgcmVwb3J0LgpBZnRlcj1uZXR3b3JrLnRhcmdldAoKW1NlcnZpY2VdClR5cGU9c2ltcGxlClVzZXI9d3d3LWRhdGEKUmVzdGFydD1hbHdheXMKRXhlY1N0YXJ0PS91c3IvYmluL2dvYWNjZXNzIC92YXIvbG9nL25naW54L2FjY2Vzcy5sb2cqIC92YXIvbG9nL25naW54L3JldmVyc2UtYWNjZXNzLmxvZyogLW8gL3Zhci93d3cvaHRtbC9pbmRleC5odG1sIC0tbG9nLWZvcm1hdD1DT01CSU5FRCAtLXJlYWwtdGltZS1odG1sClN0YW5kYXJkT3V0cHV0PW51bGwKU3RhbmRhcmRFcnJvcj1udWxsCgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQ='

    - copy:
        dest: '/lib/systemd/system/goaccess.service'
        content: "{{ goaccess-service | b64decode }}"

    - name: chmod /var/www/html to nginx users and group
      command: chown -R www-data:www /var/www/html

    - name: Start and Enable service nginx, if not started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start and Enable service goaccess, if not started
      service:
        name: goaccess
        state: started
        enabled: yes

    - name: Reload service nginx, in all cases
      service:
        name: nginx
        state: reloaded
