version: "2"

services:
  rancher:
    image: rancher/rancher
    volumes:
      - rancher_nfs:/var/lib/rancher
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  rancher_nfs:
    driver_opts:
      type: "nfs"
      o: "addr=freenas.ad.gwebs.ca,nolock,soft,rw"
      device: ":/mnt/Vault/Configs/rancher"
